-- CREATE DATABASE BilleteraVirtualApi;
-- USE BilleteraVirtualApi;

CREATE TABLE Cuentas (
Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NombreTitular VARCHAR(100) NOT NULL,
NumeroCuenta VARCHAR(20) NOT NULL UNIQUE,
Saldo DECIMAL(18,2) NOT NULL DEFAULT 0.00
);

CREATE TABLE Categorias (
Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
Nombre VARCHAR(50) NOT NULL,
Tipo VARCHAR(10) NOT NULL -- Valores: 'INGRESO' o 'EGRESO'
);

CREATE TABLE Transacciones (
    Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CuentaId INT NOT NULL,
    CategoriaId INT NOT NULL,
    Monto DECIMAL(18,2) NOT NULL,
    Tipo VARCHAR(10) NOT NULL, -- Valores: 'INGRESO' o 'EGRESO'
    Fecha DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_Cuenta FOREIGN KEY (CuentaId) REFERENCES Cuentas(Id),
    CONSTRAINT FK_Categoria FOREIGN KEY (CategoriaId) REFERENCES Categorias(Id)
);